name: test
on:
  push:
    branches:
      - master

jobs:
  build-examples:
    name: Build examples
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: envoyproxy/envoy
          ref: release/v1.18

      - name: Install deps
        run: brew install coreutils wget cmake libtool go bazel automake ninja clang-format autoconf aspell
      
      - name: create user.bazelrc
        run: echo build --action_env=PATH="/usr/local/bin:/opt/local/bin:/usr/bin:/bin" >> user.bazelrc

      - name: Build envoy
        run: bazel build -c opt //source/exe:envoy-static

      - uses: actions/upload-artifact@v2
        with:
          name: envoy
          path: bazel-bin/source/exe/envoy-static
